IT Setup

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -51,3 +51,59 @@ jobs:
 
     - name: Test
       run: go test -v ./...
+
+    - name: Run integration test cases
+      id: integration_test
+      env:
+        INTEGRATION_TEST_CRED_PATH: ${{ secrets.INTEGRATION_TEST_CRED_PATH }}
+      run: |
+          go test integration_test.go -args -target=proxy | tee -a ${GITHUB_WORKSPACE}/integration_test_result.txt
+          go test integration_test.go -args -target=cassandra | tee -a ${GITHUB_WORKSPACE}/integration_test_result.txt ; (exit ${PIPESTATUS[0]})
+
+    - name: Comment integration test result on PR
+      uses: actions/github-script@v7
+      if: ${{ success() || failure() }}
+      continue-on-error: true
+      with:
+        script: |
+          const fs = require('fs');
+          const filePath = `${process.env.GITHUB_WORKSPACE}/integration_test_result.txt`;
+          const integration_test_result = fs.readFileSync(filePath, 'utf8');
+          
+          // Extract and format the integration test result
+          const lines = integration_test_result.split('\n');
+          let formatted_result = '### Integration Test Result\n\n';
+          formatted_result += '| Test Package             | Status | Duration  |\n';
+          formatted_result += '|--------------------------|--------|-----------|\n';
+          lines.forEach((line, index) => {
+            const match = line.match(/^(ok|FAIL)\s+(\S+)\s+([\d\.]+s)$/);
+            if (match) {
+              const status = match[1];
+              let packageName = match[2];
+              const duration = match[3];
+
+              if(index === 0) {
+                  packageName = "proxy-adaptor-integration-tests";
+              } else {
+                  packageName = "cassandra-adaptor-integration-tests";
+              }
+              formatted_result += `| ${packageName} | ${status} | ${duration} |\n`;
+            }
+          });
+
+          // Comment on the pull request using the github context
+          github.rest.issues.createComment({
+          issue_number: context.payload.pull_request.number,
+          owner: context.repo.owner,
+          repo: context.repo.repo,
+          body: `${formatted_result}\n\n${integration_test_result}\n`,
+          })
+            .then(() => {
+            console.log('Commented on the pull request successfully.');
+            // process.exit(1); // Exit the script with a failure status to fail the GitHub workflow
+          })
+            .catch((error) => {
+            console.error('Error commenting on the pull request:', error);
+            // process.exit(1);
+          });
+      
