Update CICD to Comment unit test result on PR

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -50,4 +50,33 @@ jobs:
       run: go build -v ./...
 
     - name: Test
-      run: go test -v ./...
+      run: |
+            go mod tidy
+            go test ./{/otel,/third_party/datastax/proxycore,/responsehandler,/spanner,/tableConfig,/tableConfig,/translator,/utilities,/third_party/datastax/proxy} -coverprofile=cover.out | tee -a ${GITHUB_WORKSPACE}/unit_test_result.txt ; (exit ${PIPESTATUS[0]})
+            go tool cover -func cover.out | grep total: >> ${GITHUB_WORKSPACE}/unit_test_result.txt
+
+    - name: Comment unit test result on PR
+      uses: actions/github-script@v7
+      if: ${{ success() || failure() }}
+      continue-on-error: true
+      with:
+        script: |
+          const fs = require('fs');
+          const filePath = `${process.env.GITHUB_WORKSPACE}/unit_test_result.txt`;
+          const unit_test_result = fs.readFileSync(filePath, 'utf8');
+    
+          // Comment on the pull request using the github context
+          github.rest.issues.createComment({
+          issue_number: context.payload.pull_request.number,
+          owner: context.repo.owner,
+          repo: context.repo.repo,
+          body: `### Unit test result\n\n${unit_test_result}\n`,
+          })
+            .then(() => {
+            console.log('Commented on the pull request successfully.');
+            // process.exit(1); // Exit the script with a failure status to fail the GitHub workflow
+          })
+            .catch((error) => {
+            console.error('Error commenting on the pull request:', error);
+            // process.exit(1);
+          });
